name: deploy on FTP
on:
  workflow_run:
    workflows: ["run-tests"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --omit dev
      - name: Deploy on FTP Server
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.ftp_server }}
          user: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          localDir: "build/."
          remoteDir: "./"
          options: "--delete --asci"
